version: '3'
services:
  mysql:
    build:
      context: ./build
      dockerfile: mysql.dockerfile
    #container_name: mysql
    image: mysql:0.0.8
    hostname: mysql
    ports:
    - 3306:3306
    networks:
      - wds_net
  hadoop:
    build:
      context: ./build
      dockerfile: hadoop.dockerfile
    image: hadoop:0.0.8
    hostname: hadoop
    volumes:
    - /root/docker/build/config/hadoop/etc:/opt/hadoop-2.7.2/etc
    ports:
    - 50070:50070
    - 8089:8089
    networks:
      - wds_net
  hive:
    build:
      context: ./build
      dockerfile: hive.dockerfile
    image: hive:0.0.8
    hostname: hive
    volumes:
    - /root/docker/build/config/hadoop/etc:/opt/hadoop-2.7.2/etc
    - /root/docker/build/config/hive/conf:/opt/apache-hive-2.3.3-bin/conf
    links:
    - mysql
    - hadoop
    depends_on:
    - mysql
    - hadoop
    networks:
    - wds_net
  spark:
    build:
      context: ./build
      dockerfile: spark.dockerfile
    image: spark:0.0.8
    hostname: spark
    volumes:
    - /root/docker/build/config/hadoop/etc:/opt/hadoop-2.7.2/etc
    - /root/docker/build/config/hive/conf:/opt/apache-hive-2.3.3-bin/conf
    - /root/docker/build/config/spark/conf:/opt/spark-2.4.3-bin-hadoop2.7/conf
    links:
    - mysql
    - hadoop
    - hive
    depends_on:
    - mysql
    - hadoop
    - hive
    networks:
    - wds_net
  linkis:
    build:
      context: ./build
      dockerfile: linkis.dockerfile
    image: linkis:0.0.8
    hostname: linkis
    volumes:
    - /root/docker/build/config/hadoop/etc:/opt/hadoop-2.7.2/etc
    - /root/docker/build/config/hive/conf:/opt/apache-hive-2.3.3-bin/conf
    - /root/docker/build/config/spark/conf:/opt/spark-2.4.3-bin-hadoop2.7/conf
    - /root/docker/build/config/linkis/conf:/opt/linkis/conf
    links:
    - mysql
    - hadoop
    - hive
    - spark
    depends_on:
    - mysql
    - hadoop
    - hive
    - spark
    ports:
    - 20303:20303
    - 9001:9001
    networks:
    - wds_net
  nginx:
    build:
      context: ./build
      dockerfile: nginx.dockerfile
    image: nginx:0.0.8
    hostname: nginx
    volumes:
    - /root/docker/build/config/nginx/conf.d:/etc/nginx/conf.d
    - /root/docker/build/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
    - mysql
    - hadoop
    - hive
    - spark
    - linkis
    depends_on:
    - mysql
    - hadoop
    - hive
    - spark
    - linkis
    ports:
    - 8088:8088
    networks:
    - wds_net
  dss:
    build:
      context: ./build
      dockerfile: dss.dockerfile
    image: dss:0.0.8
    hostname: dss
    volumes:
    - /root/docker/build/config/hadoop/etc:/opt/hadoop-2.7.2/etc
    - /root/docker/build/config/hive/conf:/opt/apache-hive-2.3.3-bin/conf
    - /root/docker/build/config/spark/conf:/opt/spark-2.4.3-bin-hadoop2.7/conf
    - /root/docker/build/config/dss/conf:/opt/dss/conf
    links:
    - mysql
    - hadoop
    - hive
    - spark
    - linkis
    depends_on:
    - mysql
    - hadoop
    - hive
    - spark
    - linkis
    networks:
    - wds_net

networks:
  wds_net:
    ipam:
      config:
      - subnet: "172.31.238.0/24"
