kind: Deployment
apiVersion: apps/v1
metadata:
  name: linkis-ps-publicservice
  labels:
    app: linkis-ps-publicservice
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-ps-publicservice
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linkis-ps-publicservice
        version: v1
    spec:
      volumes:
        - name: conf
          configMap:
            name: linkis-config-publicservice
            defaultMode: 420
        - name: hadoop-config
          configMap:
            name: hadoop-config
            defaultMode: 420
        - name: hive-config
          configMap:
            name: hive-config
            defaultMode: 420
        - name: spark-config
          configMap:
            name: spark-config
            defaultMode: 420
        - name: log
          emptyDir: {}
      containers:
        - name: linkis-ps-publicservice
          image: 'registry.mydomain.com/library/linkis-ps-publicservice:1.2.0'
          ports:
            - containerPort: 9106
              protocol: TCP
          env:
            - name: EUREKA_URL
              value: 'http://linkis-mg-eureka:20303/eureka/'
            - name: EUREKA_PREFER_IP
              value: 'true'
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 500Mi
          volumeMounts:
            - name: conf
              mountPath: /opt/linkis/linkis-ps-publicservice/conf/
            - name: hadoop-config
              mountPath: /usr/local/hadoop/etc/hadoop
            - name: hive-config
              mountPath: /usr/local/hive/conf
            - name: spark-config
              mountPath: /usr/local/spark/conf
            - name: log
              mountPath: /opt/linkis/linkis-ps-publicservice/logs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600