kind: Service
apiVersion: v1
metadata:
  name: headless-linkis-ps-data-source-manager
  labels:
    app: headless-linkis-ps-data-source-manager
    service: headless-linkis-ps-data-source-manager
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9106
      targetPort: 9106
  selector:
    app: linkis-ps-data-source-manager
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None