kind: Service
apiVersion: v1
metadata:
  name: headless-linkis-cg-engineconnmanager
  labels:
    app: headless-linkis-cg-engineconnmanager
    service: headless-linkis-cg-engineconnmanager
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9106
      targetPort: 9106
  selector:
    app: linkis-cg-engineconnmanager
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
