kind: Service
apiVersion: v1
metadata:
  name: headless-linkis-ps-publicservice
  labels:
    app: headless-linkis-ps-publicservice
    service: headless-linkis-ps-publicservice
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9106
      targetPort: 9106
  selector:
    app: linkis-ps-publicservice
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None